version: 0.2
env:
  variables:
    APP_NAME: "manjinder"
phases:
  install:
    runtime-versions:
      nodejs: 16.x
    commands:
      - echo install process started
      - if [ -z "${BRANCH}" ]; then echo "BRANCH not set" && exit 1 ; fi
      - if [ -z "${ENVIRONMENT}" ]; then echo "ENVIRONMENT not set" && exit 1 ; fi
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build Library process started now
      - git checkout $BRANCH
      - ng build --project=simple-website-components
      - cd dist/simple-website-components
      - npm pack
      - cd ..
      - cd .. 
      - pwd
      - ls -la
      - echo build Main Project process started now
      - npm install dist/simple-website-components/simple-website-components-0.0.1.tgz
      - npm install 
      - ng build
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - pwd
      - ls -la
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://manjindersingh.me --delete